### ISSUE TITLE
Phantom joystick input with xcb

### ISSUE THREAD

**Issue by fallahn** [LaurentGomila/SFML#776] opened 2015-01-12 11:14 UTC
As discussed with Tank:
On Ubuntu 14.04 the messages

Unable to get joystick attribute. Could not find USB device for joystick at index 0.
Unable to get joystick attribute. Could not find USB device for joystick at index 0.
Unable to get joystick attribute. Could not find USB device for joystick at index 1.
Unable to get joystick attribute. Could not find USB device for joystick at index 1.

appear at the console (without querying the controller).
When querying a controller which isn't connected via getAxisPosition() seemingly random values are returned, instead of 0

**Comment by MarioLiebisch** [comment] 2015-01-12 12:25
Interesting. I've seen those messages on Ubuntu 14.10 running inside VirtualBox. I actually thought they're caused by the virtual machine, which obviously isn't the case... It's definitely not just your system.

**Comment by zwookie** [comment] 2015-01-12 17:09
I had this issue too using Ubuntu 14.04. Same error message (except I only had 1 joystick plugged in).

**Comment by edburnett** [comment] 2015-02-03 20:06
I'm getting the same error messages on Archlinux when any controller is connected.

I'm also getting nonsensical axis values from getAxisPosition() using an xbox 360 wired controller. For instance, the center/rest position does not return a zero value, as if it's not calibrated. However a Belkin gamepad works fine and returns sane values for the axis controls. 

The xbox controllers works as expected in other games on the same system.

I posted a forum thread with more details here:  http://en.sfml-dev.org/forums/index.php?topic=17426.msg125377#msg125377

**Comment by edburnett** [comment] 2015-02-04 08:54
Rebuilding SFML from the 2.1 tag gets rid of the error messages for me - but that is probably because 2.1 did not yet have getIdentification(). The erroneous axis values remain.

**Comment by eXpl0it3r** [comment] 2015-02-04 12:29
SFML 2.1 didn't use XCB, so obviously an XCB related issue won't manifest there. :wink:

**Comment by edburnett** [comment] 2015-02-04 15:34
Yes, that was indeed the point, to test if XCB had something to do with it. ;)

The 360 controller issues persist in either version, so I'd be interested in doing whatever you guys think would be constructive for helping to track down the bug.

**Comment by MarioLiebisch** [comment] 2015-02-05 13:49
The issue here seems to be the fact that there are devices that aren't joysticks/gamepads that still use one of the `js#` virtual files.

I just checked and in my example `js0` is assigned to the "Virtual Box USB Tablet", which of course will screw up SFML assuming this is a joystick.

**Comment by binary1248** [comment] 2015-02-05 15:44
SFML currently has a (rather small) blacklist that throws out all devices that aren't joysticks as can be seen [here](https://github.com/LaurentGomila/SFML/blob/master/src/SFML/Window/Unix/JoystickImpl.cpp#L85). Currently, the blacklist consists merely of ID_INPUT_ACCELEROMETER. You can try blacklisting other things as well, such as ID_INPUT_TABLET, ID_INPUT_TOUCHPAD and ID_INPUT_TOUCHSCREEN and see if it changes anything. Alternatively, you can turn it into a whitelist that only allows ID_INPUT_JOYSTICK.

This doesn't solve the cases where the device is properly detected but wrong values are returned though.

**Comment by MarioLiebisch** [comment] 2015-02-05 16:19
Actually, I'm getting the USB error from above even with only a valid gamepad/joystick being connected (for the actual gamepad's index). So it's not really about identifying the type of input (although that's a different issue).

@fallahn What values do you get, e.g. when you don't touch the sticks? The total range of the axes is -36k to 36k, so even when centered you'll almost always have some small value, not perfect 0.

Could you try running `jstest-gtk`? For me the first two axes are the left stick, the fourth and fifth are the second stick (so the tool's display will be off).

**Comment by binary1248** [comment] 2015-03-23 13:21
@fallahn @zwookie @edburnett @MarioLiebisch Can you test #838? It should fix all the outstanding issues with joysticks on Unix.

**Closed** 2015-03-31 19:07 UTC
Labels: bug, m:sfml-window, p:linux, s:accepted
