### ISSUE TITLE
Window rendering corruption under Arch Linux x64, XFCE4, XFWM4

### ISSUE THREAD

**Issue by SuperV1234** [LaurentGomila/SFML#803] opened 2015-02-24 22:15 UTC
![Image of the bug](http://i.imgur.com/ie9b8Y6.png)

Only happens with the git version of SFML. 
Resizing the window moves the scene around unnaturally.

**Comment by MarioLiebisch** [comment] 2015-02-24 22:41
Could you provide a minimal example to reproduce the issue? After all you could just make some mistake when drawing (or not drawing) your scene. Also is the screenshot while resizing or after resizing?

**Comment by binary1248** [comment] 2015-02-24 23:58
Revisions you can try:
19920f572f070904fc4b49e322fa2aa3f4133c98 - Last commit before xcb
f464e2502af84ab4a0e8777e32e101812c4e6563 - Commit before second xcb change set
f1628577d9c3802b0b723a3546317d0373aa83bc - My fixes for GLX that got a bit messed up during the rewrite (still pending in a PR)

**Comment by SuperV1234** [comment] 2015-02-26 14:11
Issue still occurs with f162857 and f464e25.

The issue **does not occur** with commit 19920f5!

**Comment by binary1248** [comment] 2015-02-26 14:21
Hmm yeah... then it must be related to the xcb rewrite and unrelated to GLX then.

Although #780 should only be concerned with fullscreen handling, can you try de79b04e0a37f963987c9691abf0f7805f9ec0f2 too?

**Comment by KenanY** [comment] 2015-03-03 18:53
Hey everyone; first of all sorry if my issue isn't that same as @SuperV1234's, but the correlation has convinced me otherwise. I'm also on Arch Linux, and I'm trying to run nothing more than the green-circle-example from [one](http://www.sfml-dev.org/tutorials/2.2/start-linux.php#compiling-a-sfml-program) of the tutorials:

``` cpp
#include <SFML/Graphics.hpp>

int main() {
  sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");
  sf::CircleShape shape(100.f);
  shape.setFillColor(sf::Color::Green);

  while (window.isOpen()) {
    sf::Event event;

    while (window.pollEvent(event)) {
      if (event.type == sf::Event::Closed) {
        window.close();
      }
    }

    window.clear();
    window.draw(shape);
    window.display();
  }

  return 0;
}
```

I noticed on `HEAD` (https://github.com/LaurentGomila/SFML/commit/1de7644277dda67250c585dce0058ee60c3b0d33) that the green circle is not rendered. Rather, the window simply contains a piece of my wallpaper (I guess this can be considered "corruption"?).

I ran a `git bisect`, starting with https://github.com/LaurentGomila/SFML/commit/19920f572f070904fc4b49e322fa2aa3f4133c98 as a good revision (which it indeed is for me; the green circle is displayed), and it concluded that https://github.com/LaurentGomila/SFML/commit/135c1716e877464db720265f37316cbb54ef13f2 was the first commit wherein the green circle was not rendered.

Feel free to ask me to test any patches :)

**Comment by binary1248** [comment] 2015-03-07 12:48
@SuperV1234 and @KenanY can you try out e87ffb3fee7b28ea94b649fd6f6828adc86b43c2 and 7a19aab610c13267fdbba42931238e75dcd7c66d? I think I might have fixed the issue, but the changes need testing.

**Comment by SuperV1234** [comment] 2015-03-07 14:46
The corruption still occurs both with e87ffb3 and 7a19aab. @KenanY, could you confirm my results?

**Comment by KenanY** [comment] 2015-03-08 01:07
https://github.com/LaurentGomila/SFML/commit/e87ffb3fee7b28ea94b649fd6f6828adc86b43c2 didn't work but https://github.com/LaurentGomila/SFML/commit/7a19aab610c13267fdbba42931238e75dcd7c66d actually works for me.

**Comment by binary1248** [comment] 2015-03-08 19:26
@SuperV1234 and @KenanY how do you link SFML? Dynamically or statically? And did you test in debug or release or even both?

**Comment by KenanY** [comment] 2015-03-08 22:42
@binary1248 Dynamically. I had only been testing the release build type. I just tried https://github.com/LaurentGomila/SFML/commit/7a19aab610c13267fdbba42931238e75dcd7c66d with the debug build type and it works as well as in release.

**Comment by binary1248** [comment] 2015-03-08 23:59
I forgot to ask, what does your system (software and hardware) look like? @SuperV1234 what GPU(s) are you running on? @AlexAUT mentioned that it would only happen when rendering on the IGP of his Optimus setup.

**Comment by KenanY** [comment] 2015-03-12 15:34
@binary1248 I'm on a Thinkpad T440s; so, integrated graphics as well. Window manager is awesomewm (what other software might be relevant?).

**Comment by binary1248** [comment] 2015-03-12 15:37
Can you provide the full output of `glxinfo`?

**Comment by KenanY** [comment] 2015-03-12 15:58
@binary1248 Sure thing: https://gist.github.com/KenanY/299a563e158a52993d17

**Comment by binary1248** [comment] 2015-03-14 18:28
@KenanY and @SuperV1234 can you try running "problematic" applications using these specialized builds of SFML?

https://github.com/binary1248/SFML/tree/2_2_visual_diag
https://github.com/binary1248/SFML/tree/2_3_visual_diag

They will dump out information to the console about the visual that SFML selects for any windows the application creates. Copy all the output after closing the application and provide it here please. It will be easier to understand if something is not functioning correctly using this information.

@SuperV1234: Can you also provide the full output of `glxinfo` on a system where the window corruption occurs?

**Comment by KenanY** [comment] 2015-03-14 19:38
@SuperV1234 Hmm, I am unable to reproduce my issue on those branches. Here are the outputs from each: https://gist.github.com/KenanY/1f90bb02c76f0832ae29

**Comment by binary1248** [comment] 2015-03-14 19:47
@KenanY: I'm assuming the issue is resolved for you in the latest gl_dev_new then.

Still waiting for more information from @SuperV1234.

**Comment by SuperV1234** [comment] 2015-03-15 20:20
Here's my [glxinfo](http://pastebin.com/Lb5YstGp). I'm testing the specialized builds now, will report ASAP

**Comment by SuperV1234** [comment] 2015-03-15 20:39
**2_2_visual_diag** results: http://pastebin.com/PcYrgvdZ

No corruption.

**Comment by SuperV1234** [comment] 2015-03-15 20:44
**2_3_visual_diag** results: http://pastebin.com/z5Vg1GYZ

Corruption **DOES OCCUR**.

**Comment by binary1248** [comment] 2015-03-15 22:55
@SuperV1234 do you by any chance also have a dual-GPU setup? I've done a bit of reading and it seems the way they do things is to hook GLX functions to reroute rendering to a secondary display. This might be an explanation for why using glXFBConfigs doesn't work although using X visuals does.

I'll make a few changes which will change how SFML selects the FBConfig of non-legacy contexts to always use the FBConfig that is paired with the X visual that it selects from the visual enumeration. That way it SFML should end up selecting the same visual as it would have in 2.2. We'll see if that already solves the problem, if not I'll have to come up with more things to try out.

**Comment by SuperV1234** [comment] 2015-03-16 00:10
The computer that presents the issue is [an ASUS S56CM laptop](http://www.asus.com/Notebooks_Ultrabooks/S56CM/). 

The video card is a **NVIDIA® GeForce® GT 635M with 2GB DDR3 VRAM**.

Now that I think about it, I actually have to use [Bumblebee drivers](https://wiki.archlinux.org/index.php/bumblebee) on Arch Linux x64.

**Comment by binary1248** [comment] 2015-03-16 00:30
Yeah... that's what I figured. @AlexAUT already told me he had the same issue with his Optimus setup. I did a bit of reading about how it is implemented and read [this](https://github.com/amonakov/primus/blob/master/technotes.md). According to that, primus hooks GLX functions, which goes good for "well-behaved" applications, but we all know that SFML isn't necessarily "not well-behaved", it's just... different from other libraries that use a single context methodology. Something might be going wrong there, which is why I want to see if reverting back to using X visuals might avoid primus messing up framebuffer creation.

I don't know if you have already tried, but can you try forcing Delver's Choice to run using your discrete (Nvidia) GPU? If the problem disappears then it is more than likely something to do with primus or the dual-GPU setup in general.

**Comment by binary1248** [comment] 2015-03-16 01:23
Ok... after [a bit more reading](http://sourceforge.net/p/virtualgl/mailman/message/32659289/), it seems that VirtualGL (which might be what you are using) also has "issues" with XCB, which is why applications just stopped working after a "simple" upgrade from Qt4 to Qt5 (Qt5 is based on XCB while Qt4 was still Xlib). According to that thread, VirtualGL also implemented an XCB interposer in 2.4 which was only [updated in the Arch repository on 6 Feb 2015](https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/virtualgl&id=b1f2f282fa7757faf3984efd0e9a5744b6e6b1ad) by @svenstaro. If you haven't already done so, maybe you can try to update your system and the issue might be resolved.

Also, when initially reading that thread, I found the following sounded quite familiar:
> To wax philosophical, I am frankly not sure why the Qt developers chose 
> to migrate to XCB.  There may have been a legitimate reason 
> (performance, perhaps), but after 18 years as a professional developer 
> and 10 years as a professional open source developer, I have noticed a 
> trend recently whereby developers seem to want to change things just for 
> the sake of changing things (systemd, anyone?) and new code seems to be 
> valued more than old, regardless of whether the new code actually 
> represents an improvement for the end user.  I see projects re-inventing 
> the whole wheel when just changing one of the spokes would be 
> sufficient, or re-inventing the wheel so it can handle terrain that will 
> only be encountered 1% of the time, or even worse, re-inventing the 
> wheel because of the possibility of encountering terrain that, in 
> reality, will likely never be encountered.  When I see this, it doesn't 
> surprise me when I also see large-scale software projects (both open 
> source and proprietary) that have major bugs outstanding for years that 
> are just being ignored.  The modern philosophy seems to be, "Who cares 
> about bugs?  Let's hack.  We can just re-design everything from the 
> ground up, and then all of the old bugs will be gone."  Rebuilding the 
> engine instead of changing the oil.  At this point, I start shaking my 
> fist at the sky, yelling "Khhhaaaaannnnn", and telling the kids to stop 
> playing on my lawn, etc.
>
> XCB can certainly do some things that Xlib can't, but it is undeniably a 
> lower-level and less user-friendly interface-- something that is 
> appropriate as an underlying interface for Xlib but not as a replacement 
> for it.  Thus, I'm not really sure why Qt 5 chose to use it.  With few 
> applications being written with remote X11 in mind these days, the 
> ability to do asynchronous requests (one of the main selling points of 
> XCB) seems like a pretty weak argument.  I'm also noticing that the XCB 
> developers have, over time, allowed some synchronous functions to creep 
> into the API, functions that have 1:1 Xlib equivalents, thus making the 
> argument in favor of XCB even weaker.  I would be interested to see a 
> post from the Qt developers regarding why they chose to make the switch, 
> because it isn't obvious to me.

@LaurentGomila: What was the initial idea when considering migrating SFML to XCB? Because now that I think of it, the way we use it, there are really no advantages :grin:. I know I should have probably asked before the merge, but I'd still be interested knowing in retrospect as well. :wink:

**Comment by binary1248** [comment] 2015-03-16 02:06
The [primus-git package](https://aur.archlinux.org/packages/primus-git/) in the AUR looks promising. VirtualGL requires Xlib hooking, which simply doesn't work with SFML at the moment, whereas primus requires only GLX hooking which should work with SFML. Give them both and try and report back when you have the time.

**Comment by LaurentGomila** [comment] 2015-03-16 06:41
> @LaurentGomila: What was the initial idea when considering migrating SFML to XCB?

If you've ever worked with Xlib, and know that there are alternatives, you don't hesitate. As stated in #200, it's old, undocumented and buggy. Of course I wish I had specific examples to demonstrate that, but I don't remember, I haven't touch this part of the code for a long time. But there were definitely stupid problems tied to Xlib.

**Comment by binary1248** [comment] 2015-03-22 10:29
@SuperV1234 Any updates on this? Like already said, SFML with XCB won't work with an older version of VirtualGL. An update _might_ fix it, but is not guaranteed to do so. Primus on the other hand doesn't require Xlib or XCB hooking, so it is more probable to work than VirtualGL. You have a choice which implementation you use with Bumblebee, but by default VirtualGL is installed automatically by pacman. Still awaiting your test results and more information.

**Comment by SuperV1234** [comment] 2015-03-27 11:09
Corruption happens with:

`./GGJ2015`
`optirun ./GGJ2015`
`optirun -c <anything> ./GGJ2015`

---

Corruption **does not** happen with:

`primusrun ./GGJ2015`

---

Anything else to test?

**Comment by binary1248** [comment] 2015-03-27 11:59
Yeah, that's what I thought.

As already mentioned above, this problem is not caused by SFML, but rather by VirtualGL. Since VirtualGL is the default for optirun (i.e. when you don't explicitly specify -b primus), you can either make optirun always use primus as its backend (through a link, configuration, etc. I have no idea :stuck_out_tongue:), or build/install a VirtualGL version that does support XCB applications.

Qt5 users already noticed this and that's why VirtualGL [came up with a workaround just for Qt5](http://sourceforge.net/p/virtualgl/mailman/message/32970059/) in 2.4, but it should apply to SFML as well. ~~Since it is still considered a workaround _just for Qt5_, it is disabled by default and the default Arch package won't work for you. You need to specify `-DVGL_FAKEXCB=1` to CMake when building it from source, and `export VGL_FAKEXCB=1` to your environment so that VirtualGL knows to use the XCB interposer when it is run. This is described in detail [here](http://blog.fabrice-salvaire.fr/qt5-virtualgl-bumblebee.html) and [here](https://bugreports.qt.io/browse/QTBUG-33258).~~

~~Thankfully (or not?), there is a [virtualgl-svn package in the AUR](https://aur.archlinux.org/packages/virtualgl-svn/), but I don't know if it still works out of the box. So you might want to try installing that after adding `-DVGL_FAKEXCB=1` to the CMake line [in the PKGBUILD](https://aur.archlinux.org/packages/vi/virtualgl-svn/PKGBUILD) (you have experience with CMake so this shouldn't be hard to do :wink:). If it fails to build, you'll need to tweak the other settings as well.~~

Edit: Turns out @svenstaro was awesome enough to [enable the workaround in the stock package as well](https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/virtualgl&id=e985cdce69e0c5a136200f2d2e5776eb8639976b) :smiley:. In this case, all you need to to is update your virtualgl package to the latest version (2.4-2) and `export VGL_FAKEXCB=1` to your environment. When you run optirun it _should_ just work out of the box.

If this works out, don't mind reporting here and closing the issue. There is nothing SFML can do to play nice with stock VirtualGL short of reverting back to Xlib. The situation sucks, but that's politics in a nutshell :stuck_out_tongue:.

**Comment by svenstaro** [comment] 2015-03-27 12:04
Sure you're welcome.

**Comment by SuperV1234** [comment] 2015-03-27 12:13
Should `export VGL_FAKEXCB=1; optirun ./GGJ2015` work? Corruption still happens.

**Comment by SuperV1234** [comment] 2015-03-27 12:18
Nevermind, seems I had to reboot after updating `virtualgl`.
`VGL_FAKEXCB=1 optirun ../build/GGJ2015` **does not present corruption**.

**Comment by binary1248** [comment] 2015-03-27 12:21
So... should we close this issue now?

**Closed** 2015-03-27 12:50 UTC
Labels: bug, m:sfml-window, p:linux
