### ISSUE TITLE
Invoking isKeyPressed when system is asleep causes crash

### ISSUE THREAD

**Issue by tehnugget** [LaurentGomila/SFML#696] opened 2014-09-11 01:04 UTC
On a 2013 Retina Macbook running OSX Mavericks is running an SFML program that contains `sf::Keyboard::isKeyPressed(..)`, whenever the system sleeps (through closing the lid) the `HIDInputManager::isKeyPressed(..)` crashes.

Specifically, it crashes when it calls `IOHIDDeviceRef device = IOHIDElementGetDevice(*it);` in
```c++
bool HIDInputManager::isKeyPressed(Keyboard::Key key)
{
    if (!m_isValid) {
        sf::err() << "HIDInputManager is invalid." << std::endl;
        return false;
    }
    
    // state = true if at least one corresponding HID key is pressed
    bool state = false;
    
    for (IOHIDElements::iterator it = m_keys[key].begin(); it != m_keys[key].end(); ++it) {
        
        IOHIDValueRef value = 0;
        
        IOHIDDeviceRef device = IOHIDElementGetDevice(*it);
        IOHIDDeviceGetValue(device, *it, &value);
        
        if (!value) {
            
            // This means some kind of error / deconnection so we remove this
            // element from our keys
            
            CFRelease(*it);
            it = m_keys[key].erase(it);
                        
        } else if (IOHIDValueGetIntegerValue(value) == 1) {
            
            // This means the key is pressed
            state = true;
            break; // Stop here
            
        } else {
            
            // This means the key is released
        }
        
    }
    
    return state;
}
```

Minimal code required to reproduce problem:
Please note that I built SFML from source using clang++ through the c++11 specification.
Just run this code, and when the window is open, just re-open, enter password and it should crash.
```c++

#include <SFML/Graphics.hpp>

// Here is a small helper for you ! Have a look.
#include "ResourcePath.hpp"

int main(int, char const**)
{
    // Create the main window
    sf::RenderWindow window(sf::VideoMode(800, 600), "SFML window");

    // Start the game loop
    while (window.isOpen())
    {
        // Process events
        sf::Event event;
        while (window.pollEvent(event))
        {
            // Close window : exit
            if (event.type == sf::Event::Closed) {
                window.close();
            }

            // Espace pressed : exit
            if (event.type == sf::Event::KeyPressed && event.key.code == sf::Keyboard::Escape) {
                window.close();
            }
        }

        // Clear screen
        window.clear();

        if (sf::Keyboard::isKeyPressed(sf::Keyboard::Up)){
            //doesn't even need code here, code isKeyPressed crashes whenever system sleeps
        }
        
        
        // Update the window
        window.display();
    }
    
    return EXIT_SUCCESS;
}
```

**Comment by binary1248** [comment] 2015-02-24 17:26
Bump.

Is this still an issue?

**Comment by mantognini** [comment] 2015-02-24 19:24
I can't reproduce so I'm closing it. Please comment here if you are actually having the issue.

**Closed by mantognini** 2015-02-24 19:24 UTC
Labels: bug, m:sfml-window, p:osx, s:undecided

**Comment by zethon** [comment] 2022-03-20 14:30
Whatever happened to this? I see this all the time. Let your program run, walk away from computer, let the computer lock and blank the screen, come back and crash.

![image](https://user-images.githubusercontent.com/5203583/159167351-af10aeb8-2e28-455b-8251-cada25ae7da4.png)

**Comment by ChrisThrasher** [comment] 2022-03-22 16:43
I'm failing to reproduce this on macOS Monterey with SFML 2.5.1. I'm letting my computer's display go blank and lock itself but after unlocking my computer the program is still running just fine. I'm using this script to build your example program and running it from the terminal. I did have to remove `#include "ResourcePath.hpp"` to get it to compile though.
```cmake
cmake_minimum_required(VERSION 3.16)
project(test)

find_package(SFML 2.5.1 REQUIRED COMPONENTS graphics)

add_executable(test test.cpp)
target_link_libraries(test PRIVATE sfml-graphics)
target_compile_features(test PRIVATE cxx_std_11)
```

**Comment by zethon** [comment] 2022-03-23 01:06
@ChrisThrasher I think I found a reliable/was way to reproduce.

Load my game, then I do Control-Command-Q to **lock** the screen. When log back in I can reproduce the crash **if and only if** I press a key that I'm testing in my code. Hence, I'm doing `sf::Keyboard::isKeyPressed(sf::Keyboard::Up)` and I get the crash only if I press the UP arrow. If I press any other key there's no crash.

The stack looks similar: 

<img width="931" alt="image" src="https://user-images.githubusercontent.com/5203583/159601460-8e189026-ee53-4845-b5f9-737e5c1b6a80.png">

My game is fairly easy to build if you're on clang 12.0: https://github.com/zethon/ttvg The crash happens during game play, not during the menu selection (since I'm not calling `isKeyPressed` there). If need be, I can try to create a smaller example.

For what it's worth: 
<img width="698" alt="image" src="https://user-images.githubusercontent.com/5203583/159601713-4b9d1932-4ef9-48e4-9cb9-7495936529fa.png">

**Comment by zethon** [comment] 2022-03-23 01:33
I tried the original code in this thread and I could not get it to trigger the crash. *However* I did discover something else that may or may not be related.

Change the code slightly so the bottom part looks like this (and add `#include <iostream>` to the top):
```
        // Clear screen
        window.clear();

        if (sf::Keyboard::isKeyPressed(sf::Keyboard::Up))
        {
            std::cout << "hi there";
        }

        // Update the window
        window.display();
```

Now set a breakpoint on the `std::cout` line. Start the program, press UP and the breakpoint hits as expected. Now do Control-Command-Q to lock the screen, then unlock the screen and press UP again. The breakpoint never hits.

**Comment by zethon** [comment] 2022-04-11 20:34
@ChrisThrasher Should I open a new issue with this?

**Comment by eXpl0it3r** [comment] 2022-04-11 22:56
Yes, please open a new issue. It may or may not be the same issue, but with ~7.5y between the two, it's hard to say and the original information/discussion might become confusing.

Would be great if you could link this issue in your new issue and provide a complete example and reproduction steps. 🙂
